# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.
version: '3.4'

services:
  healthpairapi:
    image: healthpairapi
    build:
      context: .
      dockerfile: HealthPairAPI/Dockerfile
    ports:
      - 80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    volumes:
      - ~/.vsdbg:/remote_debugger:rw




# below is from Nick

# to run api and db in docker (debugger not possible): docker-compose --build up

# to run db in docker and api outside docker (debugger possible): docker-compose up data
#   and if you have Docker Desktop, set in user secrets: "DatabaseConnection": "NotesDbPostgreSqlDockerDesktop"

# api accessible at localhost:8000 / 192.168.99.100:8000
# db accessible at localhost:5432 / 192.168.99.100:5432

# version: '3.7'

# services:

#   web:
#     build: HealthPairAPIService
#     image: healthpairapi:1.0
#     depends_on:
#       - data
#     ports:
#       - 8000:80
#     networks:
#       - default
#     environment:
#       DatabaseConnection: HealthPairDbPostgreSqlDockerCompose
#       ConnectionStrings__HealthPairDbPostgreSqlDockerCompose: Host=data;Database=HealthPairDb;Username=postgres;Password=Pass@word
#       EnsureDatabaseCreated: 'true'
#       CorsOrigins__0: http://localhost:4200
#       UseHttpsRedirection: 'false'

#   data:
#     image: postgres:12.0
#     ports:
#       - 5432:5432
#     networks:
#       - default
#     environment:
#       POSTGRES_PASSWORD: Pass@word

# networks:
#   default:
