version: '3.7'

services:

  web:
    build:
      context: HealthPairService
      dockerfile: api.Dockerfile
    image: kyranbryant/healthpair-api:1.0

  data:
    build:
      context: HealthPairService
      dockerfile: db.Dockerfile
    image: kyranbryant/healthpair-db:1.0