apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthpair-api
  labels:
    app: healthpair
    role: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: healthpair
      role: api
  template:
    metadata:
      labels:
        app: healthpair
        role: api
    spec:
      containers:
      - name: notes-api
        image: kyranbryant/healthpair-api:1.0
        ports:
        - containerPort: 80
        env:
        - name: DatabaseConnection
          value: healthpairDbPostgreSqlK8s
        - name: ConnectionStrings__healthpairDbPostgreSqlK8s
          value: Host=healthpair-db;Username=postgres;Password=Pass@word
        - name: CorsOrigins__0
          value: http://localhost:4200
        - name: CorsOrigins__1
          value: http://192.168.99.100:4200
        - name: CorsOrigins__2
          value: http://healthpair-client.azurewebsites.net
        - name: CorsOrigins__3
          value: https://healthpair-client.azurewebsites.net
        - name: CorsOrigins__4
          value: http://2002-ng-notes-client-docker.azurewebsites.net
        - name: CorsOrigins__5
          value: https://healthpair-client-docker.azurewebsites.net
        - name: CorsOrigins__6
          value: http://a219561f758a948d793acb07ca69013c-358843724.us-east-2.elb.amazonaws.com
        - name: UseHttpsRedirection
          value: 'false'