apiVersion: v1
kind: Service
metadata:
  name: healthpair-api
  labels:
    app: healthpair
    role: api
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: healthpair
    role: api